---
title: Błąd kompilatora CS0156
ms.date: 07/20/2015
f1_keywords:
- CS0156
helpviewer_keywords:
- CS0156
ms.assetid: 32026b1b-bcd7-4464-b63f-3b38c00452a6
ms.openlocfilehash: a660a2a4c27adc327777f8b05cd183ef58bd6343
ms.sourcegitcommit: 986f836f72ef10876878bd6217174e41464c145a
ms.translationtype: MT
ms.contentlocale: pl-PL
ms.lasthandoff: 08/19/2019
ms.locfileid: "69604711"
---
# <a name="compiler-error-cs0156"></a><span data-ttu-id="6835a-102">Błąd kompilatora CS0156</span><span class="sxs-lookup"><span data-stu-id="6835a-102">Compiler Error CS0156</span></span>
<span data-ttu-id="6835a-103">Instrukcja throw bez argumentów jest niedozwolona w klauzuli finally, która jest zagnieżdżona w najbliższej otaczającej klauzuli catch</span><span class="sxs-lookup"><span data-stu-id="6835a-103">A throw statement with no arguments is not allowed in a finally clause that is nested inside the nearest enclosing catch clause</span></span>  
  
 <span data-ttu-id="6835a-104">Instrukcja [throw](../language-reference/keywords/throw.md) bez parametrów może występować tylko w klauzuli **catch** , która nie przyjmuje żadnych parametrów.</span><span class="sxs-lookup"><span data-stu-id="6835a-104">A [throw](../language-reference/keywords/throw.md) statement with no parameters can only appear in a **catch** clause that takes no parameters.</span></span>  
  
 <span data-ttu-id="6835a-105">Aby uzyskać więcej informacji, zobacz [wyjątki i obsługa wyjątków](../programming-guide/exceptions/index.md).</span><span class="sxs-lookup"><span data-stu-id="6835a-105">For more information, see [Exceptions and Exception Handling](../programming-guide/exceptions/index.md).</span></span>  
  
 <span data-ttu-id="6835a-106">Poniższy przykład generuje CS0156:</span><span class="sxs-lookup"><span data-stu-id="6835a-106">The following sample generates CS0156:</span></span>  
  
```csharp  
// CS0156.cs  
using System;  
  
namespace MyNamespace  
{  
   public class MyClass2 : Exception  
   {  
   }  
  
   public class MyClass  
   {  
      public static void Main()  
      {  
         try  
         {  
            throw;   // CS0156  
         }  
  
         catch(MyClass2)  
         {  
            throw;   // this throw is valid  
         }  
      }  
   }  
}  
```
