---
title: '&#39;CATCH&#39; bloku nigdy nie został osiągnięty, ponieważ &#39; &lt;Nazwa1&gt; &#39; dziedziczy &#39; &lt;Nazwa2&gt;&#39;'
ms.date: 07/20/2015
f1_keywords:
- BC42029
- vbc42029
helpviewer_keywords:
- BC42029
ms.assetid: 4bc84a84-ec7e-49db-8794-4fb71d36d5c0
ms.openlocfilehash: 35ca615dd8fc7bbc0b2d1ae0039e9f2e70e05df6
ms.sourcegitcommit: efff8f331fd9467f093f8ab8d23a203d6ecb5b60
ms.translationtype: MT
ms.contentlocale: pl-PL
ms.lasthandoff: 09/01/2018
ms.locfileid: "43390422"
---
# <a name="39catch39-block-never-reached-because-39ltname1gt39-inherits-from-39ltname2gt39"></a>&#39;CATCH&#39; bloku nigdy nie został osiągnięty, ponieważ &#39; &lt;Nazwa1&gt; &#39; dziedziczy &#39; &lt;Nazwa2&gt;&#39;
A `Catch` bloku w kodzie nigdy nie zostanie osiągnięty.  
  
 Domyślnie ta wiadomość jest ostrzeżenie. Aby uzyskać więcej informacji na temat ukrywania ostrzeżenia lub traktowanie ostrzeżeń jako błędy, zobacz [Konfigurowanie ostrzeżeń w języku Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic).  
  
 **Identyfikator błędu:** BC42029  
  
## <a name="to-correct-this-error"></a>Aby poprawić ten błąd  
  
-   Usunąć obce `Catch` bloku.  
  
## <a name="see-also"></a>Zobacz też  
 [Porady: testowanie kodu za pomocą bloku Try... Blok CATCH w języku Visual Basic](https://msdn.microsoft.com/library/8368e205-ed73-4185-a247-af84fb4fafa9)  
 [Try...Catch...Finally, instrukcja](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
