---
title: '&#39;CATCH&#39; blok nie został nigdy osiągnięty, ponieważ &#39; &lt;Nazwa1&gt; &#39; dziedziczy &#39; &lt;Nazwa2&gt;&#39;'
ms.date: 07/20/2015
f1_keywords:
- BC42029
- vbc42029
helpviewer_keywords:
- BC42029
ms.assetid: 4bc84a84-ec7e-49db-8794-4fb71d36d5c0
ms.openlocfilehash: d97bff73092fe1b92d2596961b0ce93c7a585bc3
ms.sourcegitcommit: 3d5d33f384eeba41b2dff79d096f47ccc8d8f03d
ms.translationtype: MT
ms.contentlocale: pl-PL
ms.lasthandoff: 05/04/2018
ms.locfileid: "33633204"
---
# <a name="39catch39-block-never-reached-because-39ltname1gt39-inherits-from-39ltname2gt39"></a>&#39;CATCH&#39; blok nie został nigdy osiągnięty, ponieważ &#39; &lt;Nazwa1&gt; &#39; dziedziczy &#39; &lt;Nazwa2&gt;&#39;
A `Catch` bloku z kodem nigdy nie zostanie osiągnięty.  
  
 Domyślnie ten komunikat jest ostrzeżenie. Aby uzyskać więcej informacji na ukrywanie ostrzeżenia lub traktowanie ostrzeżeń jako błędy, zobacz [Konfigurowanie ostrzeżeń w Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic).  
  
 **Identyfikator błędu:** BC42029  
  
## <a name="to-correct-this-error"></a>Aby poprawić ten błąd  
  
-   Usuń nadmiarowe `Catch` bloku.  
  
## <a name="see-also"></a>Zobacz też  
 [Porady: testowanie kodu za pomocą bloku Try... Blok CATCH w języku Visual Basic](http://msdn.microsoft.com/library/8368e205-ed73-4185-a247-af84fb4fafa9)  
 [Try...Catch...Finally, instrukcja](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
