---
title: Wyjątki i obsługa wyjątków — C# Przewodnik programowania
ms.custom: seodec18
ms.date: 07/20/2015
helpviewer_keywords:
- exception handling [C#]
- exceptions [C#]
- C# language, exceptions
ms.assetid: 0001887f-4fa2-47e2-8034-2819477e2344
ms.openlocfilehash: 3506406a441cb2028c00d5b8ed87b57cc6dff38b
ms.sourcegitcommit: 14ad34f7c4564ee0f009acb8bfc0ea7af3bc9541
ms.translationtype: MT
ms.contentlocale: pl-PL
ms.lasthandoff: 11/01/2019
ms.locfileid: "73423253"
---
# <a name="exceptions-and-exception-handling-c-programming-guide"></a><span data-ttu-id="13eb6-102">Wyjątki i obsługa wyjątków (Przewodnik programowania w języku C#)</span><span class="sxs-lookup"><span data-stu-id="13eb6-102">Exceptions and Exception Handling (C# Programming Guide)</span></span>

<span data-ttu-id="13eb6-103">Funkcje C# obsługi wyjątków języka ułatwiają postępowanie z wszelkimi nieoczekiwanymi lub wyjątkowymi sytuacjami, które występują, gdy program jest uruchomiony.</span><span class="sxs-lookup"><span data-stu-id="13eb6-103">The C# language's exception handling features help you deal with any unexpected or exceptional situations that occur when a program is running.</span></span> <span data-ttu-id="13eb6-104">Obsługa wyjątków używa słów kluczowych `try`, `catch` i `finally`, aby wypróbować akcje, które mogą się nie powieść, aby obsłużyć błędy w przypadku podjęcia decyzji o tym, że jest to uzasadnione, i w celu późniejszego oczyszczenia zasobów.</span><span class="sxs-lookup"><span data-stu-id="13eb6-104">Exception handling uses the `try`, `catch`, and `finally` keywords to try actions that may not succeed, to handle failures when you decide that it is reasonable to do so, and to clean up resources afterward.</span></span> <span data-ttu-id="13eb6-105">Wyjątki mogą być generowane przez środowisko uruchomieniowe języka wspólnego (CLR) przez .NET Framework lub wszystkie biblioteki innych firm lub przez kod aplikacji.</span><span class="sxs-lookup"><span data-stu-id="13eb6-105">Exceptions can be generated by the common language runtime (CLR), by the .NET Framework or any third-party libraries, or by application code.</span></span> <span data-ttu-id="13eb6-106">Wyjątki są tworzone za pomocą słowa kluczowego `throw`.</span><span class="sxs-lookup"><span data-stu-id="13eb6-106">Exceptions are created by using the `throw` keyword.</span></span>

<span data-ttu-id="13eb6-107">W wielu przypadkach wyjątek może zostać wygenerowany nie przez metodę, którą kod został wywołany bezpośrednio, ale przez inną metodę w stosie wywołań.</span><span class="sxs-lookup"><span data-stu-id="13eb6-107">In many cases, an exception may be thrown not by a method that your code has called directly, but by another method further down in the call stack.</span></span> <span data-ttu-id="13eb6-108">Gdy tak się stanie, środowisko CLR spowoduje odwinięcie stosu, szukając metody z blokiem `catch` dla określonego typu wyjątku i wykona pierwszy taki blok `catch`, który zostanie znaleziony.</span><span class="sxs-lookup"><span data-stu-id="13eb6-108">When this happens, the CLR will unwind the stack, looking for a method with a `catch` block for the specific exception type, and it will execute the first such `catch` block that if finds.</span></span> <span data-ttu-id="13eb6-109">Jeśli nie znajdzie odpowiedniego bloku `catch` w dowolnym miejscu w stosie wywołań, zakończy proces i wyświetli komunikat dla użytkownika.</span><span class="sxs-lookup"><span data-stu-id="13eb6-109">If it finds no appropriate `catch` block anywhere in the call stack, it will terminate the process and display a message to the user.</span></span>

<span data-ttu-id="13eb6-110">W tym przykładzie metoda testów dla dzielenia przez zero i przechwytywania błędu.</span><span class="sxs-lookup"><span data-stu-id="13eb6-110">In this example, a method tests for division by zero and catches the error.</span></span> <span data-ttu-id="13eb6-111">Bez obsługi wyjątków ten program zostanie przerwany z powodu **nieobsługiwanego błędu DivideByZeroException** .</span><span class="sxs-lookup"><span data-stu-id="13eb6-111">Without the exception handling, this program would terminate with a **DivideByZeroException was unhandled** error.</span></span>

[!code-csharp[csProgGuideExceptions#18](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#18)]

## <a name="exceptions-overview"></a><span data-ttu-id="13eb6-112">Przegląd wyjątków</span><span class="sxs-lookup"><span data-stu-id="13eb6-112">Exceptions Overview</span></span>

<span data-ttu-id="13eb6-113">Wyjątki mają następujące właściwości:</span><span class="sxs-lookup"><span data-stu-id="13eb6-113">Exceptions have the following properties:</span></span>  

- <span data-ttu-id="13eb6-114">Wyjątki są typami, które ostatecznie pochodzą od `System.Exception`.</span><span class="sxs-lookup"><span data-stu-id="13eb6-114">Exceptions are types that all ultimately derive from `System.Exception`.</span></span>
- <span data-ttu-id="13eb6-115">Użyj bloku `try` wokół instrukcji, które mogą zgłaszać wyjątki.</span><span class="sxs-lookup"><span data-stu-id="13eb6-115">Use a `try` block around the statements that might throw exceptions.</span></span>
- <span data-ttu-id="13eb6-116">Gdy wystąpi wyjątek w bloku `try`, przepływ sterowania przechodzi do pierwszej powiązanej procedury obsługi wyjątku, która jest obecna w dowolnym miejscu w stosie wywołań.</span><span class="sxs-lookup"><span data-stu-id="13eb6-116">Once an exception occurs in the `try` block, the flow of control jumps to the first associated exception handler that is present anywhere in the call stack.</span></span> <span data-ttu-id="13eb6-117">W C#, słowo kluczowe `catch` służy do definiowania programu obsługi wyjątków.</span><span class="sxs-lookup"><span data-stu-id="13eb6-117">In C#, the `catch` keyword is used to define an exception handler.</span></span>
- <span data-ttu-id="13eb6-118">Jeśli nie ma obsługi wyjątków dla danego wyjątku, program przestanie działać z komunikatem o błędzie.</span><span class="sxs-lookup"><span data-stu-id="13eb6-118">If no exception handler for a given exception is present, the program stops executing with an error message.</span></span>
- <span data-ttu-id="13eb6-119">Nie należy przechwytywać wyjątku, chyba że można go obsłużyć i pozostawić aplikację w znanym stanie.</span><span class="sxs-lookup"><span data-stu-id="13eb6-119">Do not catch an exception unless you can handle it and leave the application in a known state.</span></span> <span data-ttu-id="13eb6-120">Jeśli przechwytujesz `System.Exception`, ponownie zgłoś go przy użyciu słowa kluczowego `throw` na końcu bloku `catch`.</span><span class="sxs-lookup"><span data-stu-id="13eb6-120">If you catch `System.Exception`, re-throw it using the `throw` keyword at the end of the `catch` block.</span></span>
- <span data-ttu-id="13eb6-121">Jeśli blok `catch` definiuje zmienną wyjątku, można jej użyć, aby uzyskać więcej informacji na temat typu wyjątku, który wystąpił.</span><span class="sxs-lookup"><span data-stu-id="13eb6-121">If a `catch` block defines an exception variable, you can use it to obtain more information about the type of exception that occurred.</span></span>
- <span data-ttu-id="13eb6-122">Wyjątki mogą być jawnie generowane przez program za pomocą słowa kluczowego `throw`.</span><span class="sxs-lookup"><span data-stu-id="13eb6-122">Exceptions can be explicitly generated by a program by using the `throw` keyword.</span></span>
- <span data-ttu-id="13eb6-123">Obiekty wyjątków zawierają szczegółowe informacje o błędzie, takie jak stan stosu wywołań i opis tekstowy błędu.</span><span class="sxs-lookup"><span data-stu-id="13eb6-123">Exception objects contain detailed information about the error, such as the state of the call stack and a text description of the error.</span></span>
- <span data-ttu-id="13eb6-124">Kod w bloku `finally` jest wykonywany nawet wtedy, gdy zostanie zgłoszony wyjątek.</span><span class="sxs-lookup"><span data-stu-id="13eb6-124">Code in a `finally` block is executed even if an exception is thrown.</span></span> <span data-ttu-id="13eb6-125">Użyj bloku `finally` do zwolnienia zasobów, na przykład aby zamknąć wszystkie strumienie lub pliki, które zostały otwarte w bloku `try`.</span><span class="sxs-lookup"><span data-stu-id="13eb6-125">Use a `finally` block to release resources, for example to close any streams or files that were opened in the `try` block.</span></span>
- <span data-ttu-id="13eb6-126">Wyjątki zarządzane w .NET Framework są implementowane na podstawie mechanizmu obsługi wyjątków strukturalnych Win32.</span><span class="sxs-lookup"><span data-stu-id="13eb6-126">Managed exceptions in the .NET Framework are implemented on top of the Win32 structured exception handling mechanism.</span></span> <span data-ttu-id="13eb6-127">Aby uzyskać więcej informacji, zobacz [strukturalna obsługa wyjątków (C++C/)](/cpp/cpp/structured-exception-handling-c-cpp) i [kurs awarii na głębokości obsługi wyjątków strukturalnych Win32](https://bytepointer.com/resources/pietrek_crash_course_depths_of_win32_seh.htm).</span><span class="sxs-lookup"><span data-stu-id="13eb6-127">For more information, see [Structured Exception Handling (C/C++)](/cpp/cpp/structured-exception-handling-c-cpp) and [A Crash Course on the Depths of Win32 Structured Exception Handling](https://bytepointer.com/resources/pietrek_crash_course_depths_of_win32_seh.htm).</span></span>

## <a name="related-sections"></a><span data-ttu-id="13eb6-128">Sekcje pokrewne</span><span class="sxs-lookup"><span data-stu-id="13eb6-128">Related Sections</span></span>

<span data-ttu-id="13eb6-129">Więcej informacji o wyjątkach i obsłudze wyjątków można znaleźć w następujących artykułach:</span><span class="sxs-lookup"><span data-stu-id="13eb6-129">See the following articles for more information about exceptions and exception handling:</span></span>

- [<span data-ttu-id="13eb6-130">Używanie wyjątków</span><span class="sxs-lookup"><span data-stu-id="13eb6-130">Using Exceptions</span></span>](using-exceptions.md)
- [<span data-ttu-id="13eb6-131">Obsługa wyjątków</span><span class="sxs-lookup"><span data-stu-id="13eb6-131">Exception Handling</span></span>](exception-handling.md)
- [<span data-ttu-id="13eb6-132">Tworzenie i zgłaszanie wyjątków</span><span class="sxs-lookup"><span data-stu-id="13eb6-132">Creating and Throwing Exceptions</span></span>](creating-and-throwing-exceptions.md)
- [<span data-ttu-id="13eb6-133">Wyjątki generowane przez kompilator</span><span class="sxs-lookup"><span data-stu-id="13eb6-133">Compiler-Generated Exceptions</span></span>](compiler-generated-exceptions.md)
- [<span data-ttu-id="13eb6-134">Instrukcje: obsługa wyjątku za pomocą try/catch (C# Przewodnik programowania)</span><span class="sxs-lookup"><span data-stu-id="13eb6-134">How to: Handle an Exception Using try/catch (C# Programming Guide)</span></span>](how-to-handle-an-exception-using-try-catch.md)
- [<span data-ttu-id="13eb6-135">Instrukcje: wykonywanie czyszczenia kodu za pomocą instrukcji finally</span><span class="sxs-lookup"><span data-stu-id="13eb6-135">How to: Execute Cleanup Code Using finally</span></span>](how-to-execute-cleanup-code-using-finally.md)
- [<span data-ttu-id="13eb6-136">Instrukcje: przechwytywanie wyjątku typu non-CLS</span><span class="sxs-lookup"><span data-stu-id="13eb6-136">How to: Catch a non-CLS Exception</span></span>](how-to-catch-a-non-cls-exception.md)

## <a name="c-language-specification"></a><span data-ttu-id="13eb6-137">Specyfikacja języka C#</span><span class="sxs-lookup"><span data-stu-id="13eb6-137">C# Language Specification</span></span>

<span data-ttu-id="13eb6-138">Aby uzyskać więcej informacji, zobacz [wyjątki](~/_csharplang/spec/exceptions.md) w [ C# specyfikacji języka](/dotnet/csharp/language-reference/language-specification/introduction).</span><span class="sxs-lookup"><span data-stu-id="13eb6-138">For more information, see [Exceptions](~/_csharplang/spec/exceptions.md) in the [C# Language Specification](/dotnet/csharp/language-reference/language-specification/introduction).</span></span> <span data-ttu-id="13eb6-139">Specyfikacja języka jest ostatecznym źródłem informacji o składni i użyciu języka C#.</span><span class="sxs-lookup"><span data-stu-id="13eb6-139">The language specification is the definitive source for C# syntax and usage.</span></span>

## <a name="see-also"></a><span data-ttu-id="13eb6-140">Zobacz także</span><span class="sxs-lookup"><span data-stu-id="13eb6-140">See also</span></span>

- <xref:System.SystemException>
- [<span data-ttu-id="13eb6-141">Przewodnik programowania w języku C#</span><span class="sxs-lookup"><span data-stu-id="13eb6-141">C# Programming Guide</span></span>](../index.md)
- [<span data-ttu-id="13eb6-142">Słowa kluczowe języka C#</span><span class="sxs-lookup"><span data-stu-id="13eb6-142">C# Keywords</span></span>](../../language-reference/keywords/index.md)
- [<span data-ttu-id="13eb6-143">throw</span><span class="sxs-lookup"><span data-stu-id="13eb6-143">throw</span></span>](../../language-reference/keywords/throw.md)
- [<span data-ttu-id="13eb6-144">try-catch</span><span class="sxs-lookup"><span data-stu-id="13eb6-144">try-catch</span></span>](../../language-reference/keywords/try-catch.md)
- [<span data-ttu-id="13eb6-145">try-finally</span><span class="sxs-lookup"><span data-stu-id="13eb6-145">try-finally</span></span>](../../language-reference/keywords/try-finally.md)
- [<span data-ttu-id="13eb6-146">try-catch-finally</span><span class="sxs-lookup"><span data-stu-id="13eb6-146">try-catch-finally</span></span>](../../language-reference/keywords/try-catch-finally.md)
- [<span data-ttu-id="13eb6-147">Wyjątki</span><span class="sxs-lookup"><span data-stu-id="13eb6-147">Exceptions</span></span>](../../../standard/exceptions/index.md)
